name: amaranta
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.0

  provider: ^6.0.5

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/img/AmaraLogo.png
    - assets/data/ubicacion.json

  uses-material-design: true
